name: Build and Publish Unity Package

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: game-ci/setup-unity@v1
        with:
          unityVersion: 6000.0.29f1
          modules: ['unity']

      - name: Install npm packages
        run: npm install -g @unity-packages/upm-ci-utils

      - name: Install Unity package dependencies
        run: upm-ci-utils install

      - name: Build Unity package
        run: upm-ci-utils build --packagePath ./Assets/JorisHoef

      - name: Publish Unity package
        env:
          UNITY_ACCESS_TOKEN: ${{ secrets.UNITY_ACCESS_TOKEN }}
        run: upm-ci-utils publish --packagePath ./Assets/JorisHoef --registry https://artifactory.unity.com/api/npm/upm-virtual --tag release